apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: lukasbrusteinpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lukasbrusteinpipelinesjavascriptdocker 
    spec:
      containers:
        - name: lukasbrusteinpipelinesjavascriptdocker 
          image: meineecontainerregistry.azurecr.io/lukasbrusteinpipelinesjavascriptdocker
          ports:
          - containerPort: 8080